### ISSUE TITLE
Adolescent client tool changes

### ISSUE THREAD

**Issue by geoffreymuchai** [onaio/who-adolescent-hqa#82]
- [x] On Characteristic #9, an additional question was added (ch9_q5).  Answer of ‘no’ is scored 1, while answer ‘yes’ is scored 0.  Total score for adolescent client is now out of 5 instead of 4.
- [x] On Characteristic #12, ‘not applicable’ answer choice options (777) were added to ch12_q2_yes and ch12_q2_yes2.  
- [x] On Characteristic #13, ‘not applicable’ (777) was added to ch13_q5.
- [x] Addition of two questions for Characteristic #14: ch14_q1_Ptg and ch14_q1_yes5_Ptg.  For both of these, ‘yes’ is scored as 1, while ‘no’ is scored as 0.  Ch. 14 is now out of 6 instead of 4 points.
- [x] For ch. 16, addition of non-scoring ‘not applicable’ (777) to ch16_q2.
